server:
  port: 8080

database:
  dbname:
  dbuser: dbuser
  dbpassword: dbpass

api:
  servicekey: "UzbfYweZfRAZ6%2BBXk6sEMPKCdtshJ2H8BIJ%2F9GF%2BbSTnP5S8JCwyyRcqmPZRY8RCtdtg1iaRsWbVeNAOtd2edA%3D%3D"
  endpoint: "http://apis.data.go.kr/1471000/DrbEasyDrugInfoService"
  operation: "getDrbEasyDrugList"